apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
    rolearn: arn:aws:iam::518843802809:role/UdacityFlaskDeployCBKubectlRole
    username: build      


    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::518843802809:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-YM5M24LI1H4E
      username: system:node:{{EC2PrivateDNSName}}

kind: ConfigMap
metadata:
  creationTimestamp: "2022-03-11T17:37:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1342"
  uid: ee9618fe-0952-4245-bcce-0b8575d0a285
